package io.hashnut.shop.dao.model;

import java.io.Serializable;
import java.util.Date;

public class GoodsOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.GoodsOrderId
     *
     * @mbggenerated
     */
    private String goodsOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.GoodsId
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.GoodsName
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.UserId
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.PayOrderId
     *
     * @mbggenerated
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.ChannelId
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.ChannelUserId
     *
     * @mbggenerated
     */
    private String channelUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Chain
     *
     * @mbggenerated
     */
    private String chain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.ChainCode
     *
     * @mbggenerated
     */
    private String chainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.CoinCode
     *
     * @mbggenerated
     */
    private String coinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.AccessSign
     *
     * @mbggenerated
     */
    private String accessSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.UpdateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.GoodsOrderId
     *
     * @return the value of t_goods_order.GoodsOrderId
     *
     * @mbggenerated
     */
    public String getGoodsOrderId() {
        return goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.GoodsOrderId
     *
     * @param goodsOrderId the value for t_goods_order.GoodsOrderId
     *
     * @mbggenerated
     */
    public void setGoodsOrderId(String goodsOrderId) {
        this.goodsOrderId = goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.GoodsId
     *
     * @return the value of t_goods_order.GoodsId
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.GoodsId
     *
     * @param goodsId the value for t_goods_order.GoodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.GoodsName
     *
     * @return the value of t_goods_order.GoodsName
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.GoodsName
     *
     * @param goodsName the value for t_goods_order.GoodsName
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Amount
     *
     * @return the value of t_goods_order.Amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Amount
     *
     * @param amount the value for t_goods_order.Amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.UserId
     *
     * @return the value of t_goods_order.UserId
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.UserId
     *
     * @param userId the value for t_goods_order.UserId
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Status
     *
     * @return the value of t_goods_order.Status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Status
     *
     * @param status the value for t_goods_order.Status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.PayOrderId
     *
     * @return the value of t_goods_order.PayOrderId
     *
     * @mbggenerated
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.PayOrderId
     *
     * @param payOrderId the value for t_goods_order.PayOrderId
     *
     * @mbggenerated
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.ChannelId
     *
     * @return the value of t_goods_order.ChannelId
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.ChannelId
     *
     * @param channelId the value for t_goods_order.ChannelId
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.ChannelUserId
     *
     * @return the value of t_goods_order.ChannelUserId
     *
     * @mbggenerated
     */
    public String getChannelUserId() {
        return channelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.ChannelUserId
     *
     * @param channelUserId the value for t_goods_order.ChannelUserId
     *
     * @mbggenerated
     */
    public void setChannelUserId(String channelUserId) {
        this.channelUserId = channelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Chain
     *
     * @return the value of t_goods_order.Chain
     *
     * @mbggenerated
     */
    public String getChain() {
        return chain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Chain
     *
     * @param chain the value for t_goods_order.Chain
     *
     * @mbggenerated
     */
    public void setChain(String chain) {
        this.chain = chain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.ChainCode
     *
     * @return the value of t_goods_order.ChainCode
     *
     * @mbggenerated
     */
    public String getChainCode() {
        return chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.ChainCode
     *
     * @param chainCode the value for t_goods_order.ChainCode
     *
     * @mbggenerated
     */
    public void setChainCode(String chainCode) {
        this.chainCode = chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.CoinCode
     *
     * @return the value of t_goods_order.CoinCode
     *
     * @mbggenerated
     */
    public String getCoinCode() {
        return coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.CoinCode
     *
     * @param coinCode the value for t_goods_order.CoinCode
     *
     * @mbggenerated
     */
    public void setCoinCode(String coinCode) {
        this.coinCode = coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.AccessSign
     *
     * @return the value of t_goods_order.AccessSign
     *
     * @mbggenerated
     */
    public String getAccessSign() {
        return accessSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.AccessSign
     *
     * @param accessSign the value for t_goods_order.AccessSign
     *
     * @mbggenerated
     */
    public void setAccessSign(String accessSign) {
        this.accessSign = accessSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.CreateTime
     *
     * @return the value of t_goods_order.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.CreateTime
     *
     * @param createTime the value for t_goods_order.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.UpdateTime
     *
     * @return the value of t_goods_order.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.UpdateTime
     *
     * @param updateTime the value for t_goods_order.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsOrderId=").append(goodsOrderId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", amount=").append(amount);
        sb.append(", userId=").append(userId);
        sb.append(", status=").append(status);
        sb.append(", payOrderId=").append(payOrderId);
        sb.append(", channelId=").append(channelId);
        sb.append(", channelUserId=").append(channelUserId);
        sb.append(", chain=").append(chain);
        sb.append(", chainCode=").append(chainCode);
        sb.append(", coinCode=").append(coinCode);
        sb.append(", accessSign=").append(accessSign);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GoodsOrder other = (GoodsOrder) that;
        return (this.getGoodsOrderId() == null ? other.getGoodsOrderId() == null : this.getGoodsOrderId().equals(other.getGoodsOrderId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getPayOrderId() == null ? other.getPayOrderId() == null : this.getPayOrderId().equals(other.getPayOrderId()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getChannelUserId() == null ? other.getChannelUserId() == null : this.getChannelUserId().equals(other.getChannelUserId()))
            && (this.getChain() == null ? other.getChain() == null : this.getChain().equals(other.getChain()))
            && (this.getChainCode() == null ? other.getChainCode() == null : this.getChainCode().equals(other.getChainCode()))
            && (this.getCoinCode() == null ? other.getCoinCode() == null : this.getCoinCode().equals(other.getCoinCode()))
            && (this.getAccessSign() == null ? other.getAccessSign() == null : this.getAccessSign().equals(other.getAccessSign()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGoodsOrderId() == null) ? 0 : getGoodsOrderId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPayOrderId() == null) ? 0 : getPayOrderId().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getChannelUserId() == null) ? 0 : getChannelUserId().hashCode());
        result = prime * result + ((getChain() == null) ? 0 : getChain().hashCode());
        result = prime * result + ((getChainCode() == null) ? 0 : getChainCode().hashCode());
        result = prime * result + ((getCoinCode() == null) ? 0 : getCoinCode().hashCode());
        result = prime * result + ((getAccessSign() == null) ? 0 : getAccessSign().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}