server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_db?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root


hashnut:
  chain: "ETH"
  chainCode: "erc20"
  coinCode: "usdt"
  serviceType: 0
  serviceVersion: "PaymentSplitterV1_1"
  serviceId:  0
  mchAddress: "0xe1fd94f8874d698567e03f671a8c62e4e2e4be90"
  accessKeyId: "ACC_1074422330228211712"
  requestKey:  "DzcjTAT1zc5baIT1cIYl8lZsRA1FDRak"
  responseKey: "bHbb2bQTtEqE5sQCAIlZ0TiQ0gXGjEQ2"
  receiptAddress:  "0x06d403f6f80cbeecb2227cb3d39083f70426a114f"